name: Build V2Ray rules dat files
on:
  workflow_dispatch:
  schedule:
    - cron: "0 1 */3 * *"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set variables
        run: |
          echo "RELEASE_NAME=Dat Files Release" >> $GITHUB_ENV
          echo "TAG_NAME=dat-release" >> $GITHUB_ENV
        shell: bash

      - name: Checkout runetfreedom/geodat2srs
        uses: actions/checkout@v4
        with:
          repository: runetfreedom/geodat2srs
          path: geodat2srs

      - name: Get geoip.dat relative files
        run: |
          wget https://github.com/ristavor/geoip-custom/raw/release/geoip.dat
          wget https://github.com/ristavor/geoip-custom/raw/release/geoip.dat.sha256sum

      - name: Get geosite.dat relative files
        run: |
          wget https://github.com/ristavor/geosite-custom/raw/release/geosite.dat
          wget https://github.com/ristavor/geosite-custom/raw/release/geosite.dat.sha256sum

      - name: Generate sing-box srs
        run: |
          go build -C geodat2srs ./
          ./geodat2srs/geodat2srs geoip -i ./geoip.dat -o ./tmp/sing-box/rule-set-geoip/
          ./geodat2srs/geodat2srs geosite -i ./geosite.dat -o ./tmp/sing-box/rule-set-geosite/
          cd ./tmp/sing-box || exit 1
          zip -r ../../sing-box.zip *
          cd ../..
          mv ./tmp/sing-box ./sing-box

      - name: Git push assets to "release" branch
        run: |
          git init
          git config --local user.name "github-actions[bot]"
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git remote remove origin || true
          git remote add origin "https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}"

          if git ls-remote --exit-code origin release; then
            git push --delete origin release
          fi

          git checkout --orphan release
          
          git add *.dat *.sha256sum sing-box.zip sing-box
          git commit -m "${{ env.RELEASE_NAME }}"
          
          git push -f -u origin release

      - name: Release and upload assets
        run: |
          gh release upload ${{ env.TAG_NAME }} ./geosite.dat ./geosite.dat.sha256sum ./geoip.dat ./geoip.dat.sha256sum ./sing-box.zip --clobber
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

